import "./globals.css"
import {Poppins} from  "next/font/google"
import {ClerkProvider} from  "@clerk/nextjs"

const poppins = Poppins({ subsets: ['latin'], weight:"200" });
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className ={`${poppins.className} bg-gradient-to-r from-white to-gray-300`}>
       <ClerkProvider>
       {children}
       </ClerkProvider>
        
        </body>
    </html>
  )
}
